/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for class Poller
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include "lub/Poller.h"

using namespace lub;

/** lub::Poller::Poller(int reserve=8)
 * include/lub/Poller.h:93
 */
static int Poller_Poller(lua_State *L) {
  try {
    int top__ = lua_gettop(L);
    if (top__ >= 1) {
      int reserve = dub::checkint(L, 1);
      Poller *retval__ = new Poller(reserve);
      dub::pushudata(L, retval__, "lub.Poller", true);
      return 1;
    } else {
      Poller *retval__ = new Poller();
      dub::pushudata(L, retval__, "lub.Poller", true);
      return 1;
    }
  } catch (std::exception &e) {
    lua_pushfstring(L, "new: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "new: Unknown exception");
  }
  return dub::error(L);
}

/** lub::Poller::~Poller()
 * include/lub/Poller.h:95
 */
static int Poller__Poller(lua_State *L) {
  try {
    DubUserdata *userdata = ((DubUserdata*)dub::checksdata_d(L, 1, "lub.Poller"));
    if (userdata->gc) {
      Poller *self = (Poller *)userdata->ptr;
      delete self;
    }
    userdata->gc = false;
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "__gc: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "__gc: Unknown exception");
  }
  return dub::error(L);
}

/** bool lub::Poller::poll(double timeout)
 * include/lub/Poller.h:105
 */
static int Poller_poll(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    double timeout = dub::checknumber(L, 2);
    lua_pushboolean(L, self->poll(timeout));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "poll: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "poll: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lub::Poller::events(lua_State *L)
 * include/lub/Poller.h:126
 */
static int Poller_events(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    return self->events(L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "events: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "events: Unknown exception");
  }
  return dub::error(L);
}

/** int lub::Poller::add(int fd, int events)
 * include/lub/Poller.h:144
 */
static int Poller_add(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int fd = dub::checkint(L, 2);
    int events = dub::checkint(L, 3);
    lua_pushnumber(L, self->add(fd, events));
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "add: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "add: Unknown exception");
  }
  return dub::error(L);
}

/** void lub::Poller::modify(int idx, int events, lua_State *L)
 * include/lub/Poller.h:150
 */
static int Poller_modify(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int idx = dub::checkint(L, 2);
    int events = dub::checkint(L, 3);
    self->modify(idx, events, L);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "modify: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "modify: Unknown exception");
  }
  return dub::error(L);
}

/** void lub::Poller::remove(int idx)
 * include/lub/Poller.h:165
 */
static int Poller_remove(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int idx = dub::checkint(L, 2);
    self->remove(idx);
    return 0;
  } catch (std::exception &e) {
    lua_pushfstring(L, "remove: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "remove: Unknown exception");
  }
  return dub::error(L);
}

/** int lub::Poller::count()
 * include/lub/Poller.h:191
 */
static int Poller_count(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    lua_pushnumber(L, self->count());
    return 1;
  } catch (std::exception &e) {
    lua_pushfstring(L, "count: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "count: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lub::Poller::idxToPos(int idx, lua_State *L)
 * include/lub/Poller.h:198
 */
static int Poller_idxToPos(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int idx = dub::checkint(L, 2);
    return self->idxToPos(idx, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "idxToPos: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "idxToPos: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lub::Poller::posToIdx(int pos, lua_State *L)
 * include/lub/Poller.h:207
 */
static int Poller_posToIdx(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int pos = dub::checkint(L, 2);
    return self->posToIdx(pos, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "posToIdx: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "posToIdx: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lub::Poller::posToFd(int pos, lua_State *L)
 * include/lub/Poller.h:216
 */
static int Poller_posToFd(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int pos = dub::checkint(L, 2);
    return self->posToFd(pos, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "posToFd: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "posToFd: Unknown exception");
  }
  return dub::error(L);
}

/** LuaStackSize lub::Poller::posToEvent(int pos, lua_State *L)
 * include/lub/Poller.h:225
 */
static int Poller_posToEvent(lua_State *L) {
  try {
    Poller *self = *((Poller **)dub::checksdata(L, 1, "lub.Poller"));
    int pos = dub::checkint(L, 2);
    return self->posToEvent(pos, L);
  } catch (std::exception &e) {
    lua_pushfstring(L, "posToEvent: %s", e.what());
  } catch (...) {
    lua_pushfstring(L, "posToEvent: Unknown exception");
  }
  return dub::error(L);
}



// --=============================================== __tostring
static int Poller___tostring(lua_State *L) {
  Poller *self = *((Poller **)dub::checksdata_n(L, 1, "lub.Poller"));
  lua_pushfstring(L, "lub.Poller: %p (%f)", self, self-> count());
  
  return 1;
}

// --=============================================== METHODS

static const struct luaL_Reg Poller_member_methods[] = {
  { "new"          , Poller_Poller        },
  { "__gc"         , Poller__Poller       },
  { "poll"         , Poller_poll          },
  { "events"       , Poller_events        },
  { "add"          , Poller_add           },
  { "modify"       , Poller_modify        },
  { "remove"       , Poller_remove        },
  { "count"        , Poller_count         },
  { "idxToPos"     , Poller_idxToPos      },
  { "posToIdx"     , Poller_posToIdx      },
  { "posToFd"      , Poller_posToFd       },
  { "posToEvent"   , Poller_posToEvent    },
  { "__tostring"   , Poller___tostring    },
  { "deleted"      , dub::isDeleted       },
  { NULL, NULL},
};


extern "C" int luaopen_lub_Poller(lua_State *L)
{
  // Create the metatable which will contain all the member methods
  luaL_newmetatable(L, "lub.Poller");
  // <mt>

  // register member methods
  dub::fregister(L, Poller_member_methods);
  // setup meta-table
  dub::setup(L, "lub.Poller");
  // <mt>
  return 1;
}
